version: "3.9"
services:
  web:
    build: app/.
    ports:
      - 5005:5005
    env_file: 
      - app/.env
    volumes:
      - ./app/Py:/app
  redis:
    image: redis:6.0.16-alpine
    ports:
      - 6379:6379
    volumes:
      - /home/lyx/wSpace/Py/Projects/BudgetBot/redis:/data
    command: redis-server --requirepass lyxi
